### ISSUE TITLE
how to understand poolFree(xx,xx) api ?

### ISSUE THREAD

**Issue by qianguozheng** [jobtalle/pool#4]
I have take a deep look at the source, but I still cannot understand, why poolFreed structure can be used to store the freed memory address ? the structure only have a *nextFree element which mean it is just an empty list, how can you store the memory pool address in the structure , I don't understand the deep meaning , please help me, thanks ?

```
typedef struct poolFreed{
    struct poolFreed *nextFree;
} poolFreed;

void poolFree(pool *p, void *ptr)
{
    poolFreed *pFreed = p->freed;

    p->freed = ptr;
    p->freed->nextFree = pFreed;
}
```

To verify this usage, but it cannot workout, sample test code as below, it would cause SIGSEGV, what's the difference between this and the sample code?

```
#include <stdio.h>
#include <stdlib.h>

typedef struct list{
    struct list *next;
} list;

void insert(list *l, void *ptr)
{
    list *p = l;
    l = ptr;
    l->next = p;
}
int main()
{
    list root;
    //int i = 10;
    //char c = 'a';
    //double d = 100.00;
    char *i = malloc(100);
    char *c = malloc(100);
    char *d = malloc(100);

    printf("i=%p,c=%p,d=%p\n", &i, &c, &d);

    insert(&root, i);
    insert(&root, c);
    insert(&root, d);

    list *l = &root;
    while (l)
    {
        printf("list= %p\n", l);
        l = l->next;
    }
}

```

**Comment by qianguozheng** [comment]
@jobtalle @tversteeg @pradeepgoswami90

**Comment by jobtalle** [comment]
When a piece of memory is freed in the allocated memory block, it is not freed using `free`. Instead, an instance of `struct poolFreed` is placed at the memory location. This will create a linked list of freed elements, but instead of using separate memory for this linked list, it is placed in previously used memory in the pool.

The list elements only contain a next pointer, but the location of each list element is a pointer to an unused piece of memory in the pool. It does not need to point to a usable piece of memory, because its own location is that pointer.
